apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: support-bot
      namespace:
      labels:
        app: support-bot
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: support-bot
      template:
        metadata:
          labels:
            app: support-bot
      spec:
        strategy:
          type: Recreate
        containers:
          - name: support-bot
            image: support-bot:4
            ports:
              - containerPort: 9090
                protocol: TCP
            resources:
              limits:
                memory: 200Mi
              requests:
                memory: 200Mi
                cpu: "0"


